# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgurDL.ui'
#
# Created: Tue Jul 10 09:13:51 2018
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(475, 330)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 451, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_account = QtWidgets.QWidget()
        self.tab_account.setObjectName("tab_account")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_account)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 371, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_clientid = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_clientid.setContentsMargins(0, 0, 0, 0)
        self.formLayout_clientid.setObjectName("formLayout_clientid")
        self.clientIDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.clientIDLabel.setObjectName("clientIDLabel")
        self.formLayout_clientid.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clientIDLabel)
        self.clientIDLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.clientIDLineEdit.setObjectName("clientIDLineEdit")
        self.formLayout_clientid.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clientIDLineEdit)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_account)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 80, 371, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_clientsecret = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_clientsecret.setContentsMargins(0, 0, 0, 0)
        self.formLayout_clientsecret.setObjectName("formLayout_clientsecret")
        self.clientSecretLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.clientSecretLabel.setObjectName("clientSecretLabel")
        self.formLayout_clientsecret.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clientSecretLabel)
        self.clientSecretLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.clientSecretLineEdit.setObjectName("clientSecretLineEdit")
        self.formLayout_clientsecret.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clientSecretLineEdit)
        self.pushButton_submit = QtWidgets.QPushButton(self.tab_account)
        self.pushButton_submit.setGeometry(QtCore.QRect(10, 160, 421, 41))
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.label_help = QtWidgets.QLabel(self.tab_account)
        self.label_help.setGeometry(QtCore.QRect(410, 130, 16, 20))
        self.label_help.setAlignment(QtCore.Qt.AlignCenter)
        self.label_help.setObjectName("label_help")
        self.tabWidget.addTab(self.tab_account, "")
        self.tab_download = QtWidgets.QWidget()
        self.tab_download.setObjectName("tab_download")
        self.pushButton_download = QtWidgets.QPushButton(self.tab_download)
        self.pushButton_download.setGeometry(QtCore.QRect(10, 160, 421, 41))
        self.pushButton_download.setObjectName("pushButton_download")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_download)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 371, 51))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_postUrl = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_postUrl.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_postUrl.setContentsMargins(0, 0, 0, 0)
        self.formLayout_postUrl.setObjectName("formLayout_postUrl")
        self.postURLLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.postURLLabel.setObjectName("postURLLabel")
        self.formLayout_postUrl.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.postURLLabel)
        self.postURLLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.postURLLineEdit.setObjectName("postURLLineEdit")
        self.formLayout_postUrl.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.postURLLineEdit)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_download)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 80, 371, 51))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_downloadTo = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_downloadTo.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_downloadTo.setContentsMargins(0, 0, 0, 0)
        self.formLayout_downloadTo.setObjectName("formLayout_downloadTo")
        self.downloadToLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.downloadToLabel.setObjectName("downloadToLabel")
        self.formLayout_downloadTo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.downloadToLabel)
        self.downloadToLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.downloadToLineEdit.setObjectName("downloadToLineEdit")
        self.formLayout_downloadTo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.downloadToLineEdit)
        self.checkBox_metadata = QtWidgets.QCheckBox(self.tab_download)
        self.checkBox_metadata.setGeometry(QtCore.QRect(230, 120, 97, 22))
        self.checkBox_metadata.setObjectName("checkBox_metadata")
        self.checkBox_zipped = QtWidgets.QCheckBox(self.tab_download)
        self.checkBox_zipped.setGeometry(QtCore.QRect(70, 120, 78, 22))
        self.checkBox_zipped.setObjectName("checkBox_zipped")
        self.pushButton_fileExplorer = QtWidgets.QPushButton(self.tab_download)
        self.pushButton_fileExplorer.setGeometry(QtCore.QRect(400, 80, 31, 27))
        self.pushButton_fileExplorer.setObjectName("pushButton_fileExplorer")
        self.tabWidget.addTab(self.tab_download, "")
        self.tab_activity = QtWidgets.QWidget()
        self.tab_activity.setObjectName("tab_activity")
        self.tableWidget_activity = QtWidgets.QTableWidget(self.tab_activity)
        self.tableWidget_activity.setGeometry(QtCore.QRect(5, 10, 431, 192))
        self.tableWidget_activity.setObjectName("tableWidget_activity")
        self.tableWidget_activity.setColumnCount(4)
        self.tableWidget_activity.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(3, item)
        self.tableWidget_activity.horizontalHeader().setDefaultSectionSize(100)
        self.tabWidget.addTab(self.tab_activity, "")
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(120, 0, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_icon = QtWidgets.QLabel(Dialog)
        self.label_icon.setGeometry(QtCore.QRect(290, 10, 16, 41))
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ImgurDL"))
        self.clientIDLabel.setText(_translate("Dialog", "Client ID:"))
        self.clientSecretLabel.setText(_translate("Dialog", "Client Secret:"))
        self.pushButton_submit.setText(_translate("Dialog", "Submit"))
        self.label_help.setText(_translate("Dialog", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_account), _translate("Dialog", "Account"))
        self.pushButton_download.setText(_translate("Dialog", "Download"))
        self.postURLLabel.setText(_translate("Dialog", "Post URL:"))
        self.downloadToLabel.setText(_translate("Dialog", "Download to:"))
        self.checkBox_metadata.setText(_translate("Dialog", "Metadata"))
        self.checkBox_zipped.setText(_translate("Dialog", "Zipped"))
        self.pushButton_fileExplorer.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_download), _translate("Dialog", "Download"))
        item = self.tableWidget_activity.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "URL"))
        item = self.tableWidget_activity.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "# Images"))
        item = self.tableWidget_activity.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Size"))
        item = self.tableWidget_activity.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_activity), _translate("Dialog", "Activity"))
        self.label_title.setText(_translate("Dialog", "Imgur DL"))
